//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Markers"",
            ""id"": ""041cd856-59ca-48eb-b105-4529e474f7dc"",
            ""actions"": [
                {
                    ""name"": ""PlaceMarker"",
                    ""type"": ""Button"",
                    ""id"": ""bc5bebb5-1eed-403a-8cec-d0cc1737eb7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cddc7853-12ff-414b-9554-1982ab192060"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceMarker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Markers
        m_Markers = asset.FindActionMap("Markers", throwIfNotFound: true);
        m_Markers_PlaceMarker = m_Markers.FindAction("PlaceMarker", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Markers
    private readonly InputActionMap m_Markers;
    private IMarkersActions m_MarkersActionsCallbackInterface;
    private readonly InputAction m_Markers_PlaceMarker;
    public struct MarkersActions
    {
        private @InputActions m_Wrapper;
        public MarkersActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlaceMarker => m_Wrapper.m_Markers_PlaceMarker;
        public InputActionMap Get() { return m_Wrapper.m_Markers; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MarkersActions set) { return set.Get(); }
        public void SetCallbacks(IMarkersActions instance)
        {
            if (m_Wrapper.m_MarkersActionsCallbackInterface != null)
            {
                @PlaceMarker.started -= m_Wrapper.m_MarkersActionsCallbackInterface.OnPlaceMarker;
                @PlaceMarker.performed -= m_Wrapper.m_MarkersActionsCallbackInterface.OnPlaceMarker;
                @PlaceMarker.canceled -= m_Wrapper.m_MarkersActionsCallbackInterface.OnPlaceMarker;
            }
            m_Wrapper.m_MarkersActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PlaceMarker.started += instance.OnPlaceMarker;
                @PlaceMarker.performed += instance.OnPlaceMarker;
                @PlaceMarker.canceled += instance.OnPlaceMarker;
            }
        }
    }
    public MarkersActions @Markers => new MarkersActions(this);
    public interface IMarkersActions
    {
        void OnPlaceMarker(InputAction.CallbackContext context);
    }
}
