namespace HL2UnityPlugin
{
    runtimeclass HL2ResearchMode
    {
        HL2ResearchMode();

        UInt16 GetCenterDepth();
        UInt16[] GetDepthMapBuffer();
        UInt16[] GetDepthMapBufferFiltered();
        UInt8[] GetDepthMapTextureBuffer();
        UInt16[] GetShortAbImageBuffer();
        UInt8[] GetShortAbImageTextureBuffer();
        Single[] GetPointCloudBuffer();

        UInt16[] GetLongDepthMapBuffer();
        UInt8[] GetLongDepthMapTextureBuffer();

		UInt8[] GetLFCameraBuffer();
		UInt8[] GetRFCameraBuffer();
        UInt8[] GetLRCameraBuffer();
        UInt8[] GetRRCameraBuffer();
        UInt8[] GetPVColorBuffer();

        Single[] GetCenterPoint();
        Single[] GetDepthSensorPosition();
        Single[] GetDepthToWorld();
        Single[] GetCurrRotation();
        Single[] GetCurrPosition();
        Single[] GetPVMatrix();

        Int32 GetDepthBufferSize();
        Int32 GetLongDepthBufferSize();
        String PrintDepthResolution();
        String PrintDepthExtrinsics();
		String PrintLFResolution();
		String PrintLFExtrinsics();
		String PrintRFResolution();
		String PrintRFExtrinsics();

        Boolean DepthMapTextureUpdated();
        Boolean ShortAbImageTextureUpdated();
        Boolean PointCloudUpdated();
        Boolean LongDepthMapTextureUpdated();

		Boolean LFImageUpdated();
		Boolean RFImageUpdated();
        Boolean LRImageUpdated();
        Boolean RRImageUpdated();

        void InitializeDepthSensor();
        void InitializeLongDepthSensor();
        void InitializeSpatialCamerasFront();

        void StartDepthSensorLoop();
        void StartLongDepthSensorLoop();
		void StartSpatialCamerasFrontLoop();
        void StartPVCameraLoop();

        void StopAllSensorDevice();

        void SetReferenceCoordinateSystem(Windows.Perception.Spatial.SpatialCoordinateSystem refCoord);
        void SetPointCloudRoiInSpace(Single centerX, Single centerY, Single centerZ, Single boundX, Single boundY, Single boundZ);
        void SetPointCloudDepthOffset(UInt16 offset);
    }
}
